language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install six coverage
  - sudo apt-get install ffmpeg
  - python setup.py develop
script:
  - nosetests pyutils
matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
