language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install ffmpeg screen
  - travis_retry sudo pip install -e .[django,flask,ming,mongo,smpte2022] --use-mirrors
script:
  - sudo python setup.py test --extra-all
matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
