language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
install:
  - pip install six
  - python setup.py develop
script:
  - python pyutils/ffmpeg.py
  - python pyutils/filesystem.py
  - python pyutils/pyutils.py --travis
