language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - sudo apt-get install ffmpeg screen
  - git clone https://github.com/davidfischer-ch/python-fastxor.git
  - cd python-fastxor && python setup.py develop && cd ..
  - python setup.py develop
script:
  - sudo python setup.py test
matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
