language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
install:
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq screen
  - travis_retry sudo pip install -e .[atlassian,django,django_filter,django_formtools,flask,ming,mongo,rest_framework,selenium,smpte2022,voluptuous] --use-mirrors
  - travis_retry sudo pip install coveralls
script:
  - sudo python setup.py test
matrix:
  allow_failures:
    - python: 2.6
    - python: 3.2
after_success:
  coveralls
